import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";


const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  display: "swap", // optional: improves performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable}`}
      >
        <Navbar />
        {children}
      </body>

    </html>
  );
}
